### ISSUE TITLE
Logo with text should have transparent BG

### ISSUE THREAD

**Issue by belfordv** [open-rpc/design#10]
https://github.com/open-rpc/design/blob/master/png/open-rpc-logo-320x320.png

**Comment by shanejonas** [comment]
Hi @belfordv, thanks for the issue. 

Theres an alternative version here: https://raw.githubusercontent.com/open-rpc/design/master/icons/open-rpc-logo-withText/open-rpc-logo%20(PNG)/256x256.png

**Comment by BelfordZ** [comment]
you can also try this one https://github.com/open-rpc/design/blob/master/stickers/3x3_die_cut_sticker/3x3_die_cut_sticker.svg

**Comment by belfordv** [comment]
Awesome. Thanks @shanejonas !
